force-app/main/default/objects/Notify_Internal_User__mdt/Notify_Internal_User__mdt.object-meta.xml
<CustomObject>
    <label>Notify Internal User</label>
    <pluralLabel>Notify Internal Users</pluralLabel>
</CustomObject>

force-app/main/default/objects/Notify_Internal_User__mdt/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <label>Team Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Service Team</fullName>
                <default>true</default>
                <label>Customer Service Team</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/service/NotifyInternalUserMetadataService.cls
/**
 * @description       :
 * @author            : Ahmed Abdelraouf
 * @group             :
 * @last modified on  : 08-02-2024
 * @last modified by  : Ahmed Abdelraouf
 **/
public class NotifyInternalUserMetadataService {
  private static NotifyInternalUserMetadataService instance = null;

  //private constructor to avoid creating an instance anywhere outside of this class
  private NotifyInternalUserMetadataService() {
  }
  public static NotifyInternalUserMetadataService getInstance() {
    if (instance == null) {
      instance = new NotifyInternalUserMetadataService();
    }
    return instance;
  }

  public Map<String, String> mapEmailTemplatesTeamNamesByProcessName(
    String processName
  ) {
    // List<Notify_Internal_User__mdt> allValues = Notify_Internal_User__mdt.getAll()
    //   .values();
    Map<String, String> emailTemplatesByTeamNames = new Map<String, String>();
    List<Notify_Internal_User__mdt> listNotifyUserByProcess = [
      SELECT Id, Team_Name__c, Email_Template_Name__c
      FROM Notify_Internal_User__mdt
      WHERE Process_Name__c = :processName
    ];
    for (
      Notify_Internal_User__mdt notifyInternalUser : listNotifyUserByProcess
    ) {
      emailTemplatesByTeamNames.put(
        notifyInternalUser.Team_Name__c,
        notifyInternalUser.Email_Template_Name__c
      );
    }

    return emailTemplatesByTeamNames;
  }
}