force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FED-{0000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/tests/triggers/FeedbackTriggerTest.cls
/**
 * @description       :
 * @author            : Ahmed Abdelraouf
 * @group             :
 * @last modified on  : 07-30-2024
 * @last modified by  : Ahmed Abdelraouf
 **/
@isTest
public class FeedbackTriggerTest {
  public static final string ASSERT_MESSAGE_MATCHED_DEFAULT_CUSTOMER = 'Feedback record customer linked to defualt Customer';
  @isTest
  public static void testAssignDefaultCustomer() {
    Customer__c defaultCustomer = TestEntities.createDefualtCustomer(
      'default@gmail.com'
    );
    Feedback__c feedbackToInsert = TestEntitiesHelper.newFeedback(
      Datetime.Now(),
      'notdefault@gmail.com'
    );
    insert feedbackToInsert;
    Feedback__c feedbackAfterInsert = [
      SELECT Id, Customer__c
      FROM Feedback__c
      WHERE Id = :feedbackToInsert.Id
    ];

    System.assertEquals(
      defaultCustomer.Id,
      feedbackAfterInsert.Customer__c,
      ASSERT_MESSAGE_MATCHED_DEFAULT_CUSTOMER
    );
  }
  @isTest
  public static void testAssignSubmittedCustomer() {
    Customer__c defaultCustomer = TestEntities.createDefualtCustomer(
      'default@gmail.com'
    );
    Customer__c submittedCustomer = TestEntities.createDefualtCustomer(
      'notdefault@gmail.com'
    );
    Feedback__c feedbackToInsert = TestEntitiesHelper.newFeedback(
      Datetime.Now(),
      'notdefault@gmail.com'
    );
    insert feedbackToInsert;
    Feedback__c feedbackAfterInsert = [
      SELECT Id, Customer__c
      FROM Feedback__c
      WHERE Id = :feedbackToInsert.Id
    ];

    System.assertEquals(
      submittedCustomer.Id,
      feedbackAfterInsert.Customer__c,
      ASSERT_MESSAGE_MATCHED_DEFAULT_CUSTOMER
    );
  }
}