force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Default_Customer__c.field-meta.xml
<CustomField>
    <fullName>Default_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FED-{0000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Date_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_Submitted__c</fullName>
    <label>Date Submitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/LastReviewedDate__c.field-meta.xml
<CustomField>
    <fullName>LastReviewedDate__c</fullName>
    <label>LastReviewedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Submitted_Email__c.field-meta.xml
<CustomField>
    <fullName>Submitted_Email__c</fullName>
    <label>Submitted Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/tests/mock/data/TestEntitiesHelper.cls
/**
 * @description       :
 * @author            : Ahmed Abdelraouf
 * @group             :
 * @last modified on  : 07-30-2024
 * @last modified by  : Ahmed Abdelraouf
 **/
@isTest
public class TestEntitiesHelper {
  public static Account newAccount(String name) {
    Account account = new Account();
    account.Name = name;
    return Account;
  }

  public static contact newContact(
    String lastName,
    String email,
    String accountId
  ) {
    Contact contact = new Contact();
    contact.lastName = lastName;
    contact.email = email;
    contact.AccountId = accountId;
    return contact;
  }
  public static Customer__c newCustomer(
    String name,
    String contactId,
    Boolean isDefaultCustomer
  ) {
    Customer__c customer = new Customer__c();
    customer.Name = name;
    customer.Contact__c = contactId;
    customer.Default_Customer__c = isDefaultCustomer;
    return customer;
  }
  public static Feedback__c newFeedback(
    Datetime submittedDate,
    String submittedEmail
  ) {
    Feedback__c feedback = new Feedback__c();
    feedback.Date_Submitted__c = submittedDate;
    feedback.Submitted_Email__c = submittedEmail;
    return feedback;
  }
  public static Feedback__c newFeedback(
    Datetime submittedDate,
    String submittedEmail,
    String status,
    Datetime lastReviewedDate
  ) {
    Feedback__c feedback = new Feedback__c();
    feedback.Date_Submitted__c = submittedDate;
    feedback.Submitted_Email__c = submittedEmail;
    feedback.Status__c = status;
    feedback.LastReviewedDate__c = lastReviewedDate;
    return feedback;
  }
}