force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FED-{0000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <formula>Customer__r.Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Date_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_Submitted__c</fullName>
    <label>Date Submitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Feedback_Content__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Content__c</fullName>
    <label>Feedback Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/LastReviewedDate__c.field-meta.xml
<CustomField>
    <fullName>LastReviewedDate__c</fullName>
    <label>LastReviewedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FeedbackDatatableController.cls
/**
 * @description       :
 * @author            : Ahmed Abdelraouf
 * @group             :
 * @last modified on  : 08-02-2024
 * @last modified by  : Ahmed Abdelraouf
 **/
public class FeedbackDatatableController {
  @AuraEnabled(cacheable=true)
  public static FeedbackWrapper getFeedback(
    String statusFilter,
    Integer offset,
    Integer limitNo
  ) {
    System.debug('statusFilter: ' + statusFilter);
    System.debug('offset: ' + offset);
    System.debug('limitNo: ' + limitNo);

    String statusClause = (statusFilter != null &&
      statusFilter != '')
      ? ' AND Status__c = :statusFilter'
      : '';
    String queryFilter = 'WHERE Status__c != NULL ' + statusClause;
    String query =
      'SELECT ID,Customer_Email__c, Date_Submitted__c, Feedback_Content__c, LastReviewedDate__c, Status__c, Customer__r.Contact__r.Name FROM Feedback__c ' +
      queryFilter +
      ' ORDER BY Date_Submitted__c DESC';
    query += '  LIMIT :limitNo OFFSET :offset';

    String countQuery = 'SELECT COUNT() FROM Feedback__c ' + queryFilter;

    List<Feedback__c> feedbackList = Database.query(query);
    List<FeedbackWrapper.FeedbackResponseWrapper> feedbacks = new List<FeedbackWrapper.FeedbackResponseWrapper>();
    for (Feedback__c feedback : feedbackList) {
      feedbacks.add(new FeedbackWrapper.FeedbackResponseWrapper(feedback));
    }
    Integer totalRecords = (Integer) Database.countQuery(countQuery);
    System.debug('totalRecords: ' + totalRecords);
    System.debug('feedbacks: ' + feedbacks);

    return new FeedbackWrapper(feedbacks, totalRecords);
  }
}