force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FED-{0000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <formula>Customer__r.Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Date_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_Submitted__c</fullName>
    <label>Date Submitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/CustomerFeedbackControllerTest.cls
/**
 * @description       :
 * @author            : Ahmed Abdelraouf
 * @group             :
 * @last modified on  : 08-02-2024
 * @last modified by  : Ahmed Abdelraouf
 **/
@isTest
public class CustomerFeedbackControllerTest {
  @isTest
  public static void testFetchCustomersWithSearch() {
    Customer__c defaultCustomer = TestEntities.createDefualtCustomer(
      'default@gmail.com'
    );
    Customer__c submittedCustomer = TestEntities.createDefualtCustomer(
      'notdefault@gmail.com'
    );
    Feedback__c feedbackToInsert = TestEntitiesHelper.newFeedback(
      Datetime.Now(),
      'notdefault@gmail.com'
    );
    CustomerFeedbackController ccustomerFeedbackController = new CustomerFeedbackController();
    System.runAs(new User(Id = UserInfo.getUserId())) {
      Test.startTest();
      ccustomerFeedbackController.searchQuery = 'test';
      ccustomerFeedbackController.pageSize = 1;
      ccustomerFeedbackController.pageNumber = 1;

      ccustomerFeedbackController.fetchCustomers();
      ccustomerFeedbackController.nextPage();
      ccustomerFeedbackController.previousPage();
      ccustomerFeedbackController.search();
      Test.stopTest();

      List<Customer__c> customersFromSOQL = [
        SELECT
          Id,
          Name,
          Customer_Email__c,
          (
            SELECT Id, Status__c, Date_Submitted__c
            FROM Feedbacks__r
            ORDER BY Date_Submitted__c DESC
          )
        FROM Customer__c
        WHERE Name LIKE '%test%'
        ORDER BY Name
        LIMIT 2
      ];

      List<CustomerWrapper> customersFromController = ccustomerFeedbackController.customers;

      System.assertEquals(
        customersFromSOQL.size(),
        customersFromController.size()
      );
    }
  }
}