force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FED-{0000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <formula>Customer__r.Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Date_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_Submitted__c</fullName>
    <label>Date Submitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Feedback_Content__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Content__c</fullName>
    <label>Feedback Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/wrapper/FeedbackWrapper.cls
/**
 * @description       :
 * @author            : Ahmed Abdelraouf
 * @group             :
 * @last modified on  : 08-02-2024
 * @last modified by  : Ahmed Abdelraouf
 **/
public class FeedbackWrapper {
  @AuraEnabled
  public List<FeedbackResponseWrapper> feedbacks { get; set; }
  @AuraEnabled
  public Integer totalRecords { get; set; }

  public FeedbackWrapper(
    List<FeedbackResponseWrapper> feedbacks,
    Integer totalRecords
  ) {
    this.feedbacks = feedbacks;
    this.totalRecords = totalRecords;
  }

  public class FeedbackResponseWrapper {
    @AuraEnabled
    public String id { get; set; }
    @AuraEnabled
    public String feedbackText { get; set; }
    @AuraEnabled
    public DateTime dateSubmitted { get; set; }
    @AuraEnabled
    public String status { get; set; }
    @AuraEnabled
    public String customerName { get; set; }
    @AuraEnabled
    public String customerEmail { get; set; }

    public FeedbackResponseWrapper(Feedback__c feedback) {
      this.id = feedback.Id;
      this.feedbackText = feedback.Feedback_Content__c;
      this.dateSubmitted = feedback.Date_Submitted__c;
      this.status = feedback.Status__c;
      this.customerName = feedback.Customer__r.Contact__r.Name;
      this.customerEmail = feedback.Customer_Email__c;
    }
  }
}